### ISSUE TITLE
[Clarification] Unnecessary actions in cleaning the Start Menu

### ISSUE THREAD

**Issue by instead1337** [mewostick/Creosynth#10]
Hello,

I noticed in this [commit](https://github.com/mewostick/Creosynth/commit/273026e491d6bbb1df44dbff21deb07a9e73fe34) that you're using PowerShell to clean up Start Menu entries. Just a heads-up - I actually sent you that exact solution a month ago in another issue. 

Also, I noticed you're using this command in the same commit:

`- !appx: {operation: clearCache, name: '*StartMenuExperienceHost*'}`

This basically does the same thing as the PowerShell command I shared.
By the way, you should probably remove the duplication, since both commands do the same thing.

**Comment by mewostick** [comment]
Ah, right! I'll take care of duplicates once time is available.
