### ISSUE TITLE
[Question] How does your Windows Defender disabler work?

### ISSUE THREAD

**Issue by instead1337** [mewostick/Creosynth#11]
It's not really an issue, but I'm curious how you're disabling these services in [this file](https://github.com/mewostick/Creosynth/blob/main/playbook/Configuration/Tasks/defender.yml) without requiring the highest privileges. Services like `WdFilter`, `WdNisDrv`, `WdNisSvc`, and `WinDefend` are incredibly hard to disable with just workarounds. Does Windows Defender actually get disabled with this method?

**Comment by mewostick** [comment]
Once AME Wizard prompts to switch off Defender manually by user (which includes Tamper Prevention, main reason for blocking disabling of Defender) it becomes less 'strict' so it becomes possible to set those services to disabled.

Though, recently I've had some permission issues with it so I may need to test it further.
