### ISSUE TITLE
[IDEA] FlexASIO+GUI (optional) feature

### ISSUE THREAD

**Issue by MarcoRavich** [mewostick/Creosynth#13]
Well, since a new Windows11-oriented GUI by @ramiro-uziel has been recently released, it could be interesting to include @dechamps's [FlexASIO](https://github.com/dechamps/FlexASIO#readme) + [FlexASIO Fluent](https://github.com/ramiro-uziel/FlexASIO-Fluent#readme) - as an option, of course - in CS.

Screenshot:
![](https://private-user-images.githubusercontent.com/132919483/352531062-89980704-0e99-4f0e-96af-4744209ec017.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODMwMDQsIm5iZiI6MTczMDk4MjcwNCwicGF0aCI6Ii8xMzI5MTk0ODMvMzUyNTMxMDYyLTg5OTgwNzA0LTBlOTktNGYwZS05NmFmLTQ3NDQyMDllYzAxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxMjMxNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2U0OGYxZDFkN2U3OTRjNGI5ZWE4YmVhNjBmZDIwNmU0Yjg5MmFiOGM0MmVhNmI2NjI0NzQxZmQ1YzY1MGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rD-7Y-YttxDktOYNxdzBlsccnymKI-4V6MTi54CoUbE)

**Comment by mewostick** [comment]
I've made a [discussion](https://github.com/dechamps/FlexASIO/discussions/253) in the FlexASIO repository about unattended installation which could make integrating it into CS easy.

**Comment by mewostick** [comment]
Added as an optional feature in [this commit](https://github.com/mewostick/Creosynth/commit/4099b90284e29055bc6abf665043b465b32fc902). Will be available in 0.8 release!
