### ISSUE TITLE
[SUGGESTION] Don't touch keyboard and mouse buffers

### ISSUE THREAD

**Issue by instead1337** [mewostick/Creosynth#16]
Changing `MouseDataQueueSize` or `KeyboardDataQueueSize` is a bad idea because these buffers are calibrated for optimal hardware and OS performance. Reducing them can cause input drops or misinterpretations, especially with high polling rates like 1000 Hz for a mouse.  

For instance, at 1000 Hz, a mouse generates 8 bytes per poll. A smaller buffer size can overflow in milliseconds if there's even slight system lag, leading to skipped or erratic inputs. Similarly, reducing the keyboard buffer can result in lost keystrokes or incorrect simultaneous keypress handling.  

Increasing these values isn't much better - it adds latency, as inputs are delayed while the buffer fills.  

Default values balance performance and reliability. Adjusting them often causes more problems than it solves, so it's better to focus on drivers or hardware upgrades if you’re experiencing issues.

[Changed file](https://github.com/mewostick/Creosynth/commit/c7f92223726fa1149860d27cbe985d4159b14841#diff-96df899b1651c4bf426b8180eb6475d57317baf11c18c9a0bd52b3992c11470aR391)

**Comment by mewostick** [comment]
Good points, I'll remove this in the next commits.
