### ISSUE TITLE
[REPORT] 1st run feedbacks

### ISSUE THREAD

**Issue by MarcoRavich** [mewostick/Creosynth#4]
Hi there, yesterday I've tested the playbook and - except the explorerpatcher "problem" (check the [Warning section in the latest release announcement](https://github.com/valinet/ExplorerPatcher/releases/tag/22621.3880.66.5_5094108)) - the _Online installation_ - on Win 11 Pro 23H2 @ Dell OptiPlex 3000 Micro (i5 12500T/32Gb/1Tb) - works pretty well.

However, some corrections need to be made, IMHO:
1. **Hidden files:** many creators don't need to mess around with hidden - often system - files (e.g. desktop.ini) usually, so I don't think it's a good idea to enable their visualization by default (it could be asked, but I believe that who needs to unhide them should know how to do it);
2. **Selected icon blue tick:** since is more touch-oriented feature, it should be a user decision, IMHO.
3. **Defender re-enable**: the last playbook installation step shoud prompt user to re-enable it.

General considerations: given that obviously being a pre-release ongoing build, I believe that more in-depth explanation of the changes made to the system is needed (for example I've used Edge's "debloat" function unconsciously).

Today I'll perform some real-word content creation usage tests (multicam video editing - 4 x FHD video streams + 1 x 32bit fp audio stream - on Vegas Pro 21 / 22) to check the stability.

Thanks for your work.

**Comment by mewostick** [comment]
Hey, thanks for the feedback!

I'll disable showing **system** files by default and make the blue tick an option instead. And the exceptions for ExplorerPatcher as well.

As for Defender, there is an option to re-enable Defender (which reminds me I also need to make it enable Tamper Prevention) but I suppose you mean to put it as the last prompt?


> I believe that more in-depth explanation of the changes made to the system is needed (for example I've used Edge's "debloat" function unconsciously).

Yep, that's one of my goals. I've been thinking about doing something like this with the GitHub Wiki feature as going with .md files will only get me so far.


> Today I'll perform some real-word content creation usage tests (multicam video editing - 4 x FHD video streams + 1 x 32bit fp audio stream - on Vegas Pro 21 / 22) to check the stability.

Sounds good, definitely let me know if something is acting up..


I'll likely start doing some changes to the playbook over the weekend.

Thanks again!

**Comment by MarcoRavich** [comment]
Speedy-feedback: tested for about 1 hour (Vegas 21 only) without any issue...
![cryo_feed](https://github.com/user-attachments/assets/70fc2960-aed8-48f5-b197-0f6f6c0901db)

**Comment by mewostick** [comment]
I've added an explanation of what each "custom feature" (aka user choice) does to the system in the [Wiki](https://github.com/mewostick/Creosynth/wiki).

I'll close this now.
