### ISSUE TITLE
[REQ] SSD optimizations (and more)

### ISSUE THREAD

**Issue by MarcoRavich** [mewostick/Creosynth#5]
Hi there,
analyzing the @instead1337's [RapidOS](https://github.com/rapid-community/RapidOS#readme) playbook i found some interesting optimization that could be integrated for creators (better if as choice of course):

```
function Set-SSDConfiguration {
    # Check if the system has an SSD
    $systemDriveLetter = $env:SystemDrive.Substring(0, 1)
    $diskNumber = (Get-Partition -DriveLetter $systemDriveLetter).DiskNumber
    $serialNumber = (Get-Disk -Number $diskNumber).SerialNumber.TrimStart()
    $mediaType = (Get-PhysicalDisk -SerialNumber $serialNumber).MediaType

    # Apply configurations if the drive is an SSD
    if ($mediaType -eq 'SSD') {
        Write-Host "Configuring system settings for SSD..."

        # Disable ReadyBoost (Commented out due to BSOD)
        # Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\rdyboost" -Name "Start" -Value 4 -Type DWord
        # Remove-Item -Path "HKCR:\Drive\shellex\PropertySheetHandlers\{55B3A0BD-4D28-42fe-8CFB-FA3EDFF969B8}" -ErrorAction SilentlyContinue

        # Disable SysMain (Superfetch)
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\SysMain" -Name "Start" -Value 4 -Type DWord

        # Disable svsvc service
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\svsvc" -Name "Start" -Value 4 -Type DWord

        # Enable TRIM support for SSDs
        fsutil behavior set disabledeletenotify 0

        # Disable tasks related to HDD
        Disable-ScheduledTask -TaskPath "\Microsoft\Windows\Data Integrity Scan\" -TaskName "Data Integrity Scan"

        Write-Host "Configuration completed."
    } else {
        Write-Host "No SSD drive found."
    }
}
```

Source: https://github.com/rapid-community/RapidOS/blob/main/RapidOS%20Sources/Executables/MultiTool.ps1

Hope that inspires.

**Comment by mewostick** [comment]
These changes do seem rather silly. Windows automatically detects if one has an SSD and turns on TRIM, no need to fiddle in the OS. 

I wonder what's the impact of the mystery "svsvc" service in relation to an SSD.

I did only disable SysMain if I remember correctly. Likely I'll just add the "Disable tasks related to HDD" into my playbook.

**Comment by instead1337** [comment]
Hi! I know that Windows automatically detects SSDs, but in the code I meant "check if the PC has an SSD". If it has an HDD, optimizations will not be applied.

**Comment by mewostick** [comment]
> I know that Windows automatically detects SSDs, but in the code I meant "check if the PC has an SSD". If it has an HDD, optimizations will not be applied.

I was talking about the ``# Enable TRIM support for SSDs`` part there.

**Comment by instead1337** [comment]
> I was talking about the `# Enable TRIM support for SSDs` part there.
Thanks for the info i wasn't aware that the TRIM feature is enabled by default, but I’ll keep it on just in case
