### ISSUE TITLE
[ISSUE] Unable to "upgrade" an already patched OS

### ISSUE THREAD

**Issue by MarcoRavich** [mewostick/Creosynth#7]
Hi there,
yesterday I've tried to install v0.6 on already patched (with 0.5 version) 23H2 win 11 without success: in fact AME Wizard failed to detect the deactivation of Windows Defender options (probably due to some changes made to the security settings by the previous version) and refuse to go ahead.

[Defender Remover / Defender Disabler](https://github.com/ionuttbara/windows-defender-remover#readme) needed to activate the "Next" button on AME...

**Comment by mewostick** [comment]
It also seems to be happening on the AME Playbook, something may be up with AME Wizard 😵‍💫

![Screenshot_20241019-090413_1.png](https://github.com/user-attachments/assets/b4660a78-8ca8-4650-be28-ae3270ebf72b)

**Comment by mewostick** [comment]
I've experimented a bit and currently using [Defender Remover / Defender Disabler](https://github.com/ionuttbara/windows-defender-remover#readme) is the best course of action. 

Without the "DefenderToggle" requirement I run into permission issues.

**Comment by mewostick** [comment]
I may have possibly found what could be causing the issue in this case. I've removed the "defender-fix" task which happened to force some settings without ability to switch them off as user. 

This should solve this issue..

**Comment by MarcoRavich** [comment]
Hi there,
thanks a lot for your efforts !

Unfortunately (or not ?), at the moment, I'm very busy with some live audio-video footages/recordings to work on so can't make any test...

...anyway I'm following the Creosynth's and I'll test upcoming versions and will report related feedbacks ASAP.

OT: what about 24H2 support ?

**Comment by mewostick** [comment]
> OT: what about 24H2 support ?

I'll likely test enabling support for 24H2 after 0.7 would be released. I think there is still something to fix but I have little time to experiment as of right now.

**Comment by MarcoRavich** [comment]
Ok, just updated (from 0.5) to 0.7 my 24H2 install. 

Feedbacks will come.
