### ISSUE TITLE
[ISSUE] Optimizations for windowed games cause crashes to some softwares

### ISSUE THREAD

**Issue by MarcoRavich** [mewostick/Creosynth#8]
Hi there,
today I've noticed multiple crashes on certain multimedia software ([Izotope RX 11](https://www.izotope.com/en/products/rx.html) standalone editor, for example) solved by disabling the "Optimizations for windowed games" feature.
Dunno if it's my system-specific, but I think it's better to let the user choose whether to apply it or not.

Hope that helps.

**Comment by MarcoRavich** [comment]
Well, I've just installed 24H2 on my machines, but I'll revert back the testing one (the Creosynth-applied one) since some things don't work correctly.
Anyway I've manually switched it off ([Option One](https://www.elevenforum.com/t/turn-on-or-off-optimizations-for-windowed-games-in-windows-11.4943/#One) of linked document) and seems ok.

**Comment by mewostick** [comment]
The option two would tell me if it is possible to disable the window optimisations globally in the playbook. I haven't found anything else on the matter.

**Comment by mewostick** [comment]
> is possible to make it user-optionable during the playbook run?

Of course!

**Comment by mewostick** [comment]
It does seem like the only registry option to disable it is unavailable in 23H2 registry so I won't be able to make the playbook turn it off globally.

[The option one in the ElevenForum guide](https://www.elevenforum.com/t/turn-on-or-off-optimizations-for-windowed-games-in-windows-11.4943/#One) would be the way to go here
